const products = [
  {id:1,order:1,category:"cpu",label:"CPU + included cooler",image:"amd-ryzen-5-9600",imageAlt:"AMD Ryzen 5 9600 processor retail box",name:"AMD Ryzen 5 9600 with Wraith Stealth Cooler",summary:"A first-time-builder-friendly Zen 5 processor with enough cores for modern gaming, everyday multitasking, and background apps without requiring a separate cooler purchase.",bestFor:"1440p gaming and everyday use",fit:"AM5 socket · Cooler included",stats:[["Cores / threads","6 / 12"],["Clock speed","3.8–5.2 GHz"],["Total cache","38MB"],["Default power","65W"]],worksWith:"It drops directly into the motherboard’s AM5 socket, and the included Wraith Stealth cooler keeps this starter build from needing another part.",pros:["Modern Zen 5 architecture","Integrated graphics for troubleshooting","Low-power 65W design"],url:"https://amzn.to/4pMuKF8"},
  {id:2,order:2,category:"motherboard",label:"AM5 foundation",image:"msi-b850-gaming-plus-wifi",imageAlt:"MSI B850 Gaming Plus WiFi motherboard and accessories",name:"MSI B850 Gaming Plus WiFi Motherboard",summary:"The central platform for the starter build, with support for the selected Ryzen processor, DDR5 memory, multiple NVMe drives, modern networking, and future AM5 upgrades.",bestFor:"A straightforward modern platform",fit:"ATX · AM5 · DDR5 · Wi-Fi 7",stats:[["CPU socket","AM5"],["Memory","4× DDR5 · 256GB"],["M.2 storage","3 slots"],["Networking","Wi-Fi 7 · 5G LAN"]],worksWith:"MSI lists Ryzen 9000 support, AMD EXPO, dual-channel DDR5, a PCIe 5.0 x16 graphics slot, and PCIe 4.0 M.2 storage support—all matching this parts list.",pros:["Supports the Ryzen 5 9600","Built-in wireless networking","Room for later memory and storage upgrades"],url:"https://amzn.to/4fv65l9"},
  {id:3,order:3,category:"ram",label:"Matched memory kit",image:"kingston-fury-beast-32gb-ddr5",imageAlt:"Kingston FURY Beast 32GB DDR5 memory kit",name:"Kingston FURY Beast 32GB DDR5-6000 CL30 AMD EXPO Kit",summary:"A matched two-stick kit that gives the starter PC plenty of memory for gaming and multitasking while using an AMD EXPO profile designed for compatible Ryzen platforms.",bestFor:"Gaming and multitasking",fit:"2×16GB · DDR5-6000 · CL30 · EXPO",stats:[["Capacity","32GB"],["Configuration","2×16GB"],["Rated speed","6000MT/s"],["Profile","CL30 · 1.4V"]],worksWith:"The motherboard uses DDR5, supports dual-channel mode and AMD EXPO, and officially supports 6000MT/s configurations depending on the CPU and memory setup.",pros:["Matched dual-channel pair","Low CL30 latency","Comfortable capacity for current games"],url:"https://amzn.to/4fLhLio"},
  {id:4,order:4,category:"ssd",label:"Fast 2TB storage",image:"crucial-t500-2tb",imageAlt:"Crucial T500 2TB PCIe Gen4 NVMe SSD without heatsink",name:"Crucial T500 2TB PCIe Gen4 NVMe M.2 SSD",summary:"A fast, cable-free system drive with room for Windows, applications, and a useful game library. This selection is the version without its own heatsink.",bestFor:"Operating system and game library",fit:"M.2 2280 · PCIe 4.0 NVMe",stats:[["Capacity","2TB"],["Interface","PCIe 4.0 NVMe"],["Read speed","Up to 7,400MB/s"],["Write speed","Up to 7,000MB/s"]],worksWith:"The B850 board includes an M.2 slot that supports PCIe 4.0 x4 and 2280 drives, so the non-heatsink T500 can install beneath the motherboard’s M.2 cooling cover.",pros:["Fast Gen4 performance","Two-terabyte capacity","No power or data cables"],url:"https://amzn.to/4g3gEfg"},
  {id:5,order:5,category:"gpu",label:"1440p graphics card",image:"pny-rtx-5070-oc",imageAlt:"PNY GeForce RTX 5070 OC Triple Fan graphics card and retail box",name:"PNY NVIDIA GeForce RTX 5070 OC Triple Fan 12GB",summary:"The main gaming component in this starter PC, built for high-quality 1440p play with NVIDIA Blackwell features, DLSS 4 support, and triple-fan cooling.",bestFor:"High-quality 1440p gaming",fit:"PCIe 5.0 x16 · 2.4 slots · 299.7mm",stats:[["CUDA cores","6,144"],["Graphics memory","12GB GDDR7"],["Board power","250W"],["Card length","299.7mm"]],worksWith:"It uses the motherboard’s main x16 slot, fits inside the case with about 100mm of listed length clearance, and pairs with a 750W PSU above PNY’s 650W system recommendation.",pros:["12GB GDDR7 memory","Three DisplayPort plus one HDMI","Triple-fan cooling design"],url:"https://amzn.to/4yOZadX"},
  {id:6,order:6,category:"psu",label:"Modern power supply",image:"corsair-rm750e",imageAlt:"Corsair RM750e 750W fully modular power supply",name:"Corsair RM750e 750W Fully Modular ATX 3.1 Power Supply",summary:"A compact modern power supply with enough capacity for the selected components and fully modular cables that make a first build easier to organize.",bestFor:"Powering the complete starter build",fit:"750W · Fully modular · ATX 3.1",stats:[["Rated output","750W"],["GPU cable","12V-2x6 · 600W"],["Efficiency","Cybenetics Gold"],["PSU length","140mm"]],worksWith:"The RTX 5070 lists a 650W system requirement, while this unit supplies 750W and a native modern GPU cable. Its 140mm body is well under the case’s 240mm PSU limit.",pros:["ATX 3.1 and PCIe 5.1 support","Install only the cables needed","Approximately 100mm of listed case clearance"],url:"https://amzn.to/3RKEhzX"},
  {id:7,order:7,category:"case",label:"Airflow-focused case",image:"montech-air-903-max",imageAlt:"Montech AIR 903 MAX airflow gaming PC case",name:"Montech AIR 903 MAX Case",summary:"A roomy chassis chosen to reduce the cramped feeling that makes first-time assembly harder, while including multiple large fans for airflow out of the box.",bestFor:"First-time building and airflow",fit:"ATX mid-tower · Four 140mm fans included",stats:[["Board support","E-ATX through Mini-ITX"],["GPU clearance","Up to 400mm"],["PSU clearance","Up to 240mm"],["Included fans","4× 140mm"]],worksWith:"It supports the selected ATX motherboard, allows a 400mm GPU while the PNY card is about 300mm long, and allows a 240mm PSU while the RM750e is 140mm long.",pros:["Room for every selected component","Three front and one rear fan included","Front USB-C connection"],url:"https://amzn.to/4vV2HFb"}
];
const categoryLabels={cpu:"Processor",motherboard:"Motherboard",ram:"Memory",ssd:"Storage",gpu:"Graphics card",psu:"Power supply",case:"Case"};
const state={category:"all",query:"",sort:"build-order"};
const productGrid=document.getElementById("productGrid"),resultsCount=document.getElementById("resultsCount"),emptyState=document.getElementById("emptyState"),categoryButtons=[...document.querySelectorAll("[data-category]")],productSearch=document.getElementById("productSearch"),sortProducts=document.getElementById("sortProducts"),clearFilters=document.getElementById("clearFilters");
function productImage(product){const src=`assets/products/${product.image}.svg`;return `<img class="product-photo" src="${src}" alt="${product.imageAlt}" width="520" height="260" loading="lazy" decoding="async" />`}
function productCard(product){return `<article class="product-card" id="product-${product.id}"><div class="product-visual"><span class="product-badge">${product.label}</span>${productImage(product)}</div><div class="product-content"><div class="product-type">${categoryLabels[product.category]}</div><h3>${product.name}</h3><p class="product-summary">${product.summary}</p><div class="product-meta"><div><span>Best for</span><strong>${product.bestFor}</strong></div><div><span>Compatibility</span><strong>${product.fit}</strong></div></div><div class="product-specs">${product.stats.map(([label,value])=>`<div class="product-spec"><span>${label}</span><strong>${value}</strong></div>`).join("")}</div><p class="pairing-note"><strong>Why it fits:</strong> ${product.worksWith}</p><ul class="product-pros">${product.pros.map(item=>`<li>${item}</li>`).join("")}</ul><div class="product-footer"><div class="price-band"><span>Retailer</span><strong>Check current price</strong></div><a class="product-link" href="${product.url}" target="_blank" rel="sponsored nofollow noopener" aria-label="Check current Amazon price for ${product.name}">View on Amazon</a></div></div></article>`}
function getFilteredProducts(){const filtered=products.filter(product=>{const categoryMatch=state.category==="all"||product.category===state.category;const statText=product.stats.flat().join(" ");const searchable=`${product.name} ${product.summary} ${product.category} ${product.bestFor} ${product.fit} ${statText} ${product.worksWith}`.toLowerCase();return categoryMatch&&searchable.includes(state.query)});filtered.sort(state.sort==="component"?(a,b)=>categoryLabels[a.category].localeCompare(categoryLabels[b.category]):(a,b)=>a.order-b.order);return filtered}
function renderProducts(){const filtered=getFilteredProducts();productGrid.innerHTML=filtered.map(productCard).join("");resultsCount.textContent=`${filtered.length} starter-build component${filtered.length===1?"":"s"}`;emptyState.hidden=filtered.length!==0}
function setCategory(category){state.category=category;categoryButtons.forEach(button=>button.classList.toggle("active",button.dataset.category===category));renderProducts()}
categoryButtons.forEach(button=>button.addEventListener("click",()=>{setCategory(button.dataset.category);document.getElementById("recommendations").scrollIntoView({behavior:"smooth",block:"start"})}));
productSearch.addEventListener("input",event=>{state.query=event.target.value.trim().toLowerCase();renderProducts()});
sortProducts.addEventListener("change",event=>{state.sort=event.target.value;renderProducts()});
clearFilters.addEventListener("click",()=>{state.category="all";state.query="";state.sort="build-order";productSearch.value="";sortProducts.value="build-order";categoryButtons.forEach(button=>button.classList.toggle("active",button.dataset.category==="all"));renderProducts()});
const menuButton=document.getElementById("menuButton"),mainNav=document.getElementById("mainNav");menuButton.addEventListener("click",()=>{const open=mainNav.classList.toggle("open");menuButton.setAttribute("aria-expanded",String(open))});mainNav.addEventListener("click",event=>{if(event.target.matches("a")){mainNav.classList.remove("open");menuButton.setAttribute("aria-expanded","false")}});document.getElementById("currentYear").textContent=new Date().getFullYear();renderProducts();

const pairingSection=document.getElementById('pairings');
if(pairingSection&&!pairingSection.querySelector('.bios-build-note')){
  const container=pairingSection.querySelector('.container');
  const note=document.createElement('div');
  note.className='bios-build-note';
  note.innerHTML='<strong>Socket compatibility is not the whole story.</strong><p>A motherboard may require a newer BIOS before it can boot with a supported CPU generation. Always verify the exact board model, revision, CPU-support list and required BIOS version.</p><a href="cpu-motherboard-bios-compatibility-guide.html">Read the CPU and BIOS compatibility guide →</a>';
  container.appendChild(note);
  const style=document.createElement('style');style.textContent='.bios-build-note{margin-top:28px;padding:22px;border:1px solid rgba(241,224,198,.2);border-radius:18px;background:rgba(255,255,255,.045)}.bios-build-note p{line-height:1.7}.bios-build-note a{color:#f2d19a;font-weight:800}';document.head.appendChild(style);
}
