const cpus=[
{name:'AMD Ryzen 5 5600',socket:'AM4',score:78,power:65},{name:'AMD Ryzen 5 7600',socket:'AM5',score:108,power:65},{name:'AMD Ryzen 5 9600',socket:'AM5',score:120,power:65},{name:'AMD Ryzen 7 5700X3D',socket:'AM4',score:112,power:105},{name:'AMD Ryzen 7 5800X3D',socket:'AM4',score:118,power:105},{name:'AMD Ryzen 7 7700',socket:'AM5',score:116,power:65},{name:'AMD Ryzen 7 7800X3D',socket:'AM5',score:148,power:120},{name:'AMD Ryzen 7 9700X',socket:'AM5',score:138,power:65},{name:'AMD Ryzen 7 9800X3D',socket:'AM5',score:172,power:120},{name:'AMD Ryzen 9 7900X',socket:'AM5',score:135,power:170},{name:'AMD Ryzen 9 7950X3D',socket:'AM5',score:160,power:120},{name:'AMD Ryzen 9 9950X3D',socket:'AM5',score:185,power:170},{name:'Intel Core i5-12400F',socket:'LGA1700',score:82,power:117},{name:'Intel Core i5-12600K',socket:'LGA1700',score:101,power:150},{name:'Intel Core i5-13400F',socket:'LGA1700',score:98,power:148},{name:'Intel Core i5-13600K',socket:'LGA1700',score:126,power:181},{name:'Intel Core i5-14400F',socket:'LGA1700',score:105,power:148},{name:'Intel Core i5-14600K',socket:'LGA1700',score:132,power:181},{name:'Intel Core i7-12700K',socket:'LGA1700',score:112,power:190},{name:'Intel Core i7-13700K',socket:'LGA1700',score:133,power:253},{name:'Intel Core i7-14700K',socket:'LGA1700',score:143,power:253},{name:'Intel Core i9-12900K',socket:'LGA1700',score:120,power:241},{name:'Intel Core i9-13900K',socket:'LGA1700',score:140,power:253},{name:'Intel Core i9-14900K',socket:'LGA1700',score:147,power:253},{name:'Intel Core Ultra 5 245K',socket:'LGA1851',score:128,power:159},{name:'Intel Core Ultra 7 265K',socket:'LGA1851',score:140,power:250},{name:'Intel Core Ultra 9 285K',socket:'LGA1851',score:146,power:250}
];
const gpus=[
{name:'NVIDIA GeForce RTX 3060 12GB',score:70,power:170,length:242},{name:'NVIDIA GeForce RTX 3060 Ti',score:82,power:200,length:242},{name:'NVIDIA GeForce RTX 3070',score:92,power:220,length:242},{name:'NVIDIA GeForce RTX 3080',score:118,power:320,length:285},{name:'NVIDIA GeForce RTX 3090',score:130,power:350,length:313},{name:'NVIDIA GeForce RTX 4060',score:76,power:115,length:200},{name:'NVIDIA GeForce RTX 4060 Ti 8GB',score:91,power:160,length:240},{name:'NVIDIA GeForce RTX 4070',score:112,power:200,length:244},{name:'NVIDIA GeForce RTX 4070 Super',score:127,power:220,length:244},{name:'NVIDIA GeForce RTX 4070 Ti Super',score:145,power:285,length:285},{name:'NVIDIA GeForce RTX 4080 Super',score:175,power:320,length:310},{name:'NVIDIA GeForce RTX 4090',score:215,power:450,length:336},{name:'NVIDIA GeForce RTX 5060',score:94,power:145,length:242},{name:'NVIDIA GeForce RTX 5060 Ti 16GB',score:111,power:180,length:245},{name:'NVIDIA GeForce RTX 5070',score:138,power:250,length:300},{name:'NVIDIA GeForce RTX 5070 Ti',score:160,power:300,length:304},{name:'NVIDIA GeForce RTX 5080',score:192,power:360,length:304},{name:'NVIDIA GeForce RTX 5090',score:240,power:575,length:336},{name:'AMD Radeon RX 6600',score:65,power:132,length:269},{name:'AMD Radeon RX 6650 XT',score:75,power:176,length:269},{name:'AMD Radeon RX 6700 XT',score:88,power:230,length:267},{name:'AMD Radeon RX 6800 XT',score:119,power:300,length:267},{name:'AMD Radeon RX 6950 XT',score:132,power:335,length:267},{name:'AMD Radeon RX 7600',score:73,power:165,length:204},{name:'AMD Radeon RX 7700 XT',score:103,power:245,length:267},{name:'AMD Radeon RX 7800 XT',score:121,power:263,length:267},{name:'AMD Radeon RX 7900 GRE',score:132,power:260,length:276},{name:'AMD Radeon RX 7900 XT',score:155,power:315,length:276},{name:'AMD Radeon RX 7900 XTX',score:178,power:355,length:287},{name:'AMD Radeon RX 9060 XT 16GB',score:108,power:160,length:240},{name:'AMD Radeon RX 9070',score:145,power:220,length:290},{name:'AMD Radeon RX 9070 XT',score:164,power:304,length:304},{name:'Intel Arc A750',score:68,power:225,length:280},{name:'Intel Arc A770 16GB',score:76,power:225,length:280},{name:'Intel Arc B580',score:90,power:190,length:272}
];
const boards=[
{name:'MSI B550 Tomahawk',socket:'AM4',memory:'DDR4'},{name:'ASUS TUF Gaming B550-Plus',socket:'AM4',memory:'DDR4'},{name:'MSI B650 Gaming Plus WiFi',socket:'AM5',memory:'DDR5'},{name:'MSI B850 Gaming Plus WiFi',socket:'AM5',memory:'DDR5'},{name:'ASUS TUF Gaming B650-Plus WiFi',socket:'AM5',memory:'DDR5'},{name:'Gigabyte B650 AORUS Elite AX',socket:'AM5',memory:'DDR5'},{name:'ASUS ROG Strix X670E-E Gaming WiFi',socket:'AM5',memory:'DDR5'},{name:'MSI PRO B660M-A DDR4',socket:'LGA1700',memory:'DDR4'},{name:'MSI PRO B760-P WiFi DDR4',socket:'LGA1700',memory:'DDR4'},{name:'MSI PRO B760-P WiFi DDR5',socket:'LGA1700',memory:'DDR5'},{name:'ASUS TUF Gaming Z790-Plus WiFi',socket:'LGA1700',memory:'DDR5'},{name:'Gigabyte Z790 AORUS Elite AX',socket:'LGA1700',memory:'DDR5'},{name:'ASUS TUF Gaming Z890-Plus WiFi',socket:'LGA1851',memory:'DDR5'},{name:'MSI MAG Z890 Tomahawk WiFi',socket:'LGA1851',memory:'DDR5'}
];
const cases=[
{name:'Montech AIR 903 MAX',clearance:400},{name:'Corsair 4000D Airflow',clearance:360},{name:'Corsair 5000D Airflow',clearance:400},{name:'NZXT H5 Flow',clearance:365},{name:'NZXT H7 Flow',clearance:410},{name:'Lian Li Lancool 216',clearance:392},{name:'Lian Li O11 Dynamic EVO',clearance:426},{name:'Fractal Design North',clearance:355},{name:'Fractal Design Meshify 2 Compact',clearance:341},{name:'Phanteks XT Pro Ultra',clearance:415},{name:'Cooler Master NR200P',clearance:330}
];
const $=id=>document.getElementById(id);
const normalize=value=>value.trim().toLowerCase();
function populate(listId,data){$(listId).innerHTML=data.map(item=>`<option value="${item.name}"></option>`).join('')}
populate('cpuOptions',cpus);populate('gpuOptions',gpus);populate('boardOptions',boards);populate('caseOptions',cases);
function findPart(data,value){return data.find(item=>normalize(item.name)===normalize(value))}
function num(id){const value=Number($(id).value);return Number.isFinite(value)&&value>0?value:null}
function addCheck(checks,type,title,text){checks.push({type,title,text})}
function analyze(){
 const cpuKnown=findPart(cpus,$('cpuInput').value),gpuKnown=findPart(gpus,$('gpuInput').value),boardKnown=findPart(boards,$('boardInput').value),caseKnown=findPart(cases,$('caseInput').value);
 const cpu={name:$('cpuInput').value||'Unspecified CPU',socket:cpuKnown?.socket||$('manualCpuSocket').value.trim(),score:cpuKnown?.score||num('manualCpuScore'),power:cpuKnown?.power||num('manualCpuPower')};
 const gpu={name:$('gpuInput').value||'Unspecified GPU',score:gpuKnown?.score||num('manualGpuScore'),power:gpuKnown?.power||num('manualGpuPower'),length:gpuKnown?.length||num('manualGpuLength')};
 const board={name:$('boardInput').value||'Unspecified motherboard',socket:boardKnown?.socket||$('manualBoardSocket').value.trim(),memory:boardKnown?.memory||$('manualBoardMemory').value};
 const pcCase={name:$('caseInput').value||'Unspecified case',clearance:caseKnown?.clearance||num('manualCaseClearance')};
 const resolution=Number($('resolution').value),fps=Number($('targetFps').value),game=$('gameType').value,ram=Number($('ramCapacity').value),ramType=$('ramType').value,psu=Number($('psuWattage').value);
 const checks=[];
 if(cpu.socket&&board.socket)addCheck(checks,cpu.socket.toUpperCase()===board.socket.toUpperCase()?'good':'bad','CPU and motherboard socket',cpu.socket.toUpperCase()===board.socket.toUpperCase()?`${cpu.socket} matches ${board.socket}.`:`${cpu.socket} does not match ${board.socket}. These parts cannot be installed together.`);else addCheck(checks,'warn','CPU and motherboard socket','Enter both socket types to verify platform compatibility.');
 if(board.memory)addCheck(checks,board.memory===ramType?'good':'bad','RAM and motherboard memory type',board.memory===ramType?`${ramType} matches the motherboard.`:`The motherboard uses ${board.memory}, but ${ramType} was selected.`);else addCheck(checks,'warn','RAM compatibility','Enter the motherboard memory type to verify DDR compatibility.');
 if(gpu.length&&pcCase.clearance)addCheck(checks,gpu.length<=pcCase.clearance?'good':'bad','GPU physical clearance',gpu.length<=pcCase.clearance?`${gpu.length}mm GPU fits within the listed ${pcCase.clearance}mm clearance.`:`${gpu.length}mm GPU exceeds the listed ${pcCase.clearance}mm clearance.`);else addCheck(checks,'warn','GPU physical clearance','Enter GPU length and case clearance to verify fit.');
 let recommendedPsu=null;if(cpu.power&&gpu.power){recommendedPsu=Math.ceil((cpu.power+gpu.power+100)*1.35/50)*50;addCheck(checks,psu>=recommendedPsu?'good':psu>=recommendedPsu-100?'warn':'bad','Power-supply headroom',psu>=recommendedPsu?`${psu}W meets this tool’s estimated ${recommendedPsu}W planning target.`:`Estimated planning target is about ${recommendedPsu}W; selected unit is ${psu}W.`)}else addCheck(checks,'warn','Power estimate','Enter CPU and GPU power values for a PSU estimate.');
 addCheck(checks,ram>=32?'good':ram>=16?'warn':'bad','Memory capacity',ram>=32?`${ram}GB is comfortable for modern gaming and multitasking.`:ram>=16?'16GB is still workable, but newer games and background apps can push it.':'8GB is restrictive for many modern gaming PCs.');
 let balanceTitle='More information needed',balanceText='Enter relative CPU and GPU scores to estimate gaming balance.',status='Incomplete estimate',cpuDemand=null,gpuDemand=null;
 if(cpu.score&&gpu.score){
   const resolutionGpu={1080:.82,1440:1,2160:1.33}[resolution];
   const fpsCpu=Math.max(.72,Math.min(1.55,fps/144));
   const gameCpu={balanced:1,esports:1.22,aaa:.86,simulation:1.32}[game];
   const gameGpu={balanced:1,esports:.86,aaa:1.22,simulation:.9}[game];
   cpuDemand=cpu.score/(fpsCpu*gameCpu);gpuDemand=gpu.score/(resolutionGpu*gameGpu);
   const ratio=cpuDemand/gpuDemand;
   if(ratio<.76){status='CPU-limited tendency';balanceTitle='The CPU is more likely to limit this target';balanceText=`At ${resolution}p and ${fps} FPS, this combination places comparatively more pressure on the CPU. Lowering graphics settings may not greatly increase frame rate in CPU-heavy moments.`}
   else if(ratio>1.32){status='GPU-limited tendency';balanceTitle='The GPU is more likely to limit this target';balanceText=`At ${resolution}p and ${fps} FPS, the graphics card is likely to be the main performance limit. Lower settings, upscaling, or a stronger GPU would have the largest effect.`}
   else {status='Reasonably balanced';balanceTitle='The CPU and GPU look reasonably matched';balanceText=`For this resolution, frame-rate target, and game type, neither component appears dramatically out of proportion. Individual games can still behave differently.`}
 }
 const blocking=checks.some(c=>c.type==='bad');if(blocking)status='Compatibility problem found';
 $('resultsPanel').innerHTML=`<span class="result-status">${status}</span><h2>${balanceTitle}</h2><p class="result-summary">${balanceText}</p><div class="score-row"><div class="score-card"><span>CPU</span><strong>${cpu.name}</strong></div><div class="score-card"><span>GPU</span><strong>${gpu.name}</strong></div></div><div class="check-list">${checks.map(c=>`<div class="check-item ${c.type}"><b>${c.title}</b><p>${c.text}</p></div>`).join('')}</div><p class="manual-note">Relative scores are broad planning values, not measured FPS. Always verify the exact motherboard CPU-support list, BIOS version, PSU connector requirements, RAM support, and manufacturer case-clearance notes before buying.</p>`;
}
$('calculateButton').addEventListener('click',analyze);
$('resetCalculator').addEventListener('click',()=>{$('builderForm').reset();$('resultsPanel').innerHTML='<div class="empty-results"><div class="result-icon">PC</div><h2>Your analysis will appear here</h2><p>Select known products or enter manual specifications, then analyze the configuration.</p></div>'});
const menuButton=$('menuButton'),mainNav=$('mainNav');menuButton.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});mainNav.addEventListener('click',event=>{if(event.target.matches('a')){mainNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}});$('currentYear').textContent=new Date().getFullYear();
